In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('train.csv')
df

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0        1          60       RL         65.0     8450   Pave   NaN      Reg   
1        2          20       RL         80.0     9600   Pave   NaN      Reg   
2        3          60       RL         68.0    11250   Pave   NaN      IR1   
3        4          70       RL         60.0     9550   Pave   NaN      IR1   
4        5          60       RL         84.0    14260   Pave   NaN      IR1   
...    ...         ...      ...          ...      ...    ...   ...      ...   
1455  1456          60       RL         62.0     7917   Pave   NaN      Reg   
1456  1457          20       RL         85.0    13175   Pave   NaN      Reg   
1457  1458          70       RL         66.0     9042   Pave   NaN      Reg   
1458  1459          20       RL         68.0     9717   Pave   NaN      Reg   
1459  1460          20       RL         75.0     9937   Pave   NaN      Reg   

     LandContour Utilities  ... PoolArea PoolQC  Fence MiscFeature MiscVal  \
0            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
2            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
3            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
4            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
...          ...       ...  ...      ...    ...    ...         ...     ...   
1455         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1456         Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0   
1457         Lvl    AllPub  ...        0    NaN  GdPrv        Shed    2500   
1458         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1459         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   

     MoSold YrSold  SaleType  SaleCondition  SalePrice  
0         2   2008        WD         Normal     208500  
1         5   2007        WD         Normal     181500  
2         9   2008        WD         Normal     223500  
3         2   2006        WD        Abnorml     140000  
4        12   2008        WD         Normal     250000  
...     ...    ...       ...            ...        ...  
1455      8   2007        WD         Normal     175000  
1456      2   2010        WD         Normal     210000  
1457      5   2010        WD         Normal     266500  
1458      4   2010        WD         Normal     142125  
1459      6   2008        WD         Normal     147500  

[1460 rows x 81 columns]

In [3]:
df.shape

(1460, 81)

In [4]:
null_features=[feature for feature in df.columns if df[feature].isnull().sum()>0]
null_features

['LotFrontage',
 'Alley',
 'MasVnrType',
 'MasVnrArea',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Electrical',
 'FireplaceQu',
 'GarageType',
 'GarageYrBlt',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PoolQC',
 'Fence',
 'MiscFeature']

In [5]:
len(null_features)

19

In [6]:
def null_info(df):
    null_features=[feature for feature in df.columns if df[feature].isnull().sum()>0]
    null_values_per_feature=[]
    percentage_null_values_per_feature=[]
    for feature in null_features:
        null_values=df[feature].isnull().sum()
        percentage_null_values=null_values/len(df)*100
        null_values_per_feature.append(null_values)
        percentage_null_values_per_feature.append(percentage_null_values)
    df_null=pd.DataFrame(list(zip(null_features,null_values_per_feature,percentage_null_values_per_feature)),columns=['Null_feature','Null_values','Percentage of Null values'])
    return df_null

In [10]:
df_null=null_info(df)
df_null

Null_feature  Null_values  Percentage of Null values
0    LotFrontage          259                  17.739726
1          Alley         1369                  93.767123
2     MasVnrType            8                   0.547945
3     MasVnrArea            8                   0.547945
4       BsmtQual           37                   2.534247
5       BsmtCond           37                   2.534247
6   BsmtExposure           38                   2.602740
7   BsmtFinType1           37                   2.534247
8   BsmtFinType2           38                   2.602740
9     Electrical            1                   0.068493
10   FireplaceQu          690                  47.260274
11    GarageType           81                   5.547945
12   GarageYrBlt           81                   5.547945
13  GarageFinish           81                   5.547945
14    GarageQual           81                   5.547945
15    GarageCond           81                   5.547945
16        PoolQC         1453                  99.520548
17         Fence         1179                  80.753425
18   MiscFeature         1406                  96.301370

In [14]:
df_null_40_plus=df_null[df_null['Percentage of Null values']>=40]
df_null_40_plus

Null_feature  Null_values  Percentage of Null values
1         Alley         1369                  93.767123
10  FireplaceQu          690                  47.260274
16       PoolQC         1453                  99.520548
17        Fence         1179                  80.753425
18  MiscFeature         1406                  96.301370

In [15]:
plus_40_null_features=list(df_null_40_plus['Null_feature'])
plus_40_null_features

['Alley', 'FireplaceQu', 'PoolQC', 'Fence', 'MiscFeature']

In [16]:
len(plus_40_null_features)

5

In [17]:
df[plus_40_null_features]

Alley FireplaceQu PoolQC  Fence MiscFeature
0      NaN         NaN    NaN    NaN         NaN
1      NaN          TA    NaN    NaN         NaN
2      NaN          TA    NaN    NaN         NaN
3      NaN          Gd    NaN    NaN         NaN
4      NaN          TA    NaN    NaN         NaN
...    ...         ...    ...    ...         ...
1455   NaN          TA    NaN    NaN         NaN
1456   NaN          TA    NaN  MnPrv         NaN
1457   NaN          Gd    NaN  GdPrv        Shed
1458   NaN         NaN    NaN    NaN         NaN
1459   NaN         NaN    NaN    NaN         NaN

[1460 rows x 5 columns]

In [23]:
df1=df.drop(plus_40_null_features,axis='columns')
df1

Id  MSSubClass MSZoning  LotFrontage  LotArea Street LotShape  \
0        1          60       RL         65.0     8450   Pave      Reg   
1        2          20       RL         80.0     9600   Pave      Reg   
2        3          60       RL         68.0    11250   Pave      IR1   
3        4          70       RL         60.0     9550   Pave      IR1   
4        5          60       RL         84.0    14260   Pave      IR1   
...    ...         ...      ...          ...      ...    ...      ...   
1455  1456          60       RL         62.0     7917   Pave      Reg   
1456  1457          20       RL         85.0    13175   Pave      Reg   
1457  1458          70       RL         66.0     9042   Pave      Reg   
1458  1459          20       RL         68.0     9717   Pave      Reg   
1459  1460          20       RL         75.0     9937   Pave      Reg   

     LandContour Utilities LotConfig  ... EnclosedPorch 3SsnPorch ScreenPorch  \
0            Lvl    AllPub    Inside  ...             0         0           0   
1            Lvl    AllPub       FR2  ...             0         0           0   
2            Lvl    AllPub    Inside  ...             0         0           0   
3            Lvl    AllPub    Corner  ...           272         0           0   
4            Lvl    AllPub       FR2  ...             0         0           0   
...          ...       ...       ...  ...           ...       ...         ...   
1455         Lvl    AllPub    Inside  ...             0         0           0   
1456         Lvl    AllPub    Inside  ...             0         0           0   
1457         Lvl    AllPub    Inside  ...             0         0           0   
1458         Lvl    AllPub    Inside  ...           112         0           0   
1459         Lvl    AllPub    Inside  ...             0         0           0   

     PoolArea MiscVal MoSold  YrSold  SaleType  SaleCondition  SalePrice  
0           0       0      2    2008        WD         Normal     208500  
1           0       0      5    2007        WD         Normal     181500  
2           0       0      9    2008        WD         Normal     223500  
3           0       0      2    2006        WD        Abnorml     140000  
4           0       0     12    2008        WD         Normal     250000  
...       ...     ...    ...     ...       ...            ...        ...  
1455        0       0      8    2007        WD         Normal     175000  
1456        0       0      2    2010        WD         Normal     210000  
1457        0    2500      5    2010        WD         Normal     266500  
1458        0       0      4    2010        WD         Normal     142125  
1459        0       0      6    2008        WD         Normal     147500  

[1460 rows x 76 columns]

In [24]:
df1.shape

(1460, 76)

In [25]:
numerical_features=[feature for feature in df1.columns if df1[feature].dtype!='O']
numerical_features

['Id',
 'MSSubClass',
 'LotFrontage',
 'LotArea',
 'OverallQual',
 'OverallCond',
 'YearBuilt',
 'YearRemodAdd',
 'MasVnrArea',
 'BsmtFinSF1',
 'BsmtFinSF2',
 'BsmtUnfSF',
 'TotalBsmtSF',
 '1stFlrSF',
 '2ndFlrSF',
 'LowQualFinSF',
 'GrLivArea',
 'BsmtFullBath',
 'BsmtHalfBath',
 'FullBath',
 'HalfBath',
 'BedroomAbvGr',
 'KitchenAbvGr',
 'TotRmsAbvGrd',
 'Fireplaces',
 'GarageYrBlt',
 'GarageCars',
 'GarageArea',
 'WoodDeckSF',
 'OpenPorchSF',
 'EnclosedPorch',
 '3SsnPorch',
 'ScreenPorch',
 'PoolArea',
 'MiscVal',
 'MoSold',
 'YrSold',
 'SalePrice']

In [26]:
len(numerical_features)

38

In [27]:
catagarical_features=[feature for feature in df1.columns if df1[feature].dtype=='O']
catagarical_features

['MSZoning',
 'Street',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'RoofStyle',
 'RoofMatl',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 'KitchenQual',
 'Functional',
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PavedDrive',
 'SaleType',
 'SaleCondition']

In [28]:
len(catagarical_features)

38

In [29]:
catg2_features=[feature for feature in catagarical_features if len(df1[feature].unique())==2]
catg2_features

['Street', 'Utilities', 'CentralAir']

In [30]:
for feature in catg2_features:
    df1[feature]=df1[feature].replace([df1[feature].unique()[0],df1[feature].unique()[1]],[0,1])

In [31]:
catg3_features=[feature for feature in catagarical_features if len(df1[feature].unique())==3]
catg3_features

['LandSlope', 'PavedDrive']

In [32]:
df1.shape

(1460, 76)

In [33]:
df2=df1.copy()
for feature in catg3_features:
    dummies=pd.get_dummies(df2[feature])
    df2=pd.concat([df2,dummies],axis='columns')
    df2=df2.drop([feature,dummies.columns[-1]],axis='columns')
df2

Id  MSSubClass MSZoning  LotFrontage  LotArea  Street LotShape  \
0        1          60       RL         65.0     8450       0      Reg   
1        2          20       RL         80.0     9600       0      Reg   
2        3          60       RL         68.0    11250       0      IR1   
3        4          70       RL         60.0     9550       0      IR1   
4        5          60       RL         84.0    14260       0      IR1   
...    ...         ...      ...          ...      ...     ...      ...   
1455  1456          60       RL         62.0     7917       0      Reg   
1456  1457          20       RL         85.0    13175       0      Reg   
1457  1458          70       RL         66.0     9042       0      Reg   
1458  1459          20       RL         68.0     9717       0      Reg   
1459  1460          20       RL         75.0     9937       0      Reg   

     LandContour  Utilities LotConfig  ... MiscVal MoSold YrSold SaleType  \
0            Lvl          0    Inside  ...       0      2   2008       WD   
1            Lvl          0       FR2  ...       0      5   2007       WD   
2            Lvl          0    Inside  ...       0      9   2008       WD   
3            Lvl          0    Corner  ...       0      2   2006       WD   
4            Lvl          0       FR2  ...       0     12   2008       WD   
...          ...        ...       ...  ...     ...    ...    ...      ...   
1455         Lvl          0    Inside  ...       0      8   2007       WD   
1456         Lvl          0    Inside  ...       0      2   2010       WD   
1457         Lvl          0    Inside  ...    2500      5   2010       WD   
1458         Lvl          0    Inside  ...       0      4   2010       WD   
1459         Lvl          0    Inside  ...       0      6   2008       WD   

     SaleCondition  SalePrice  Gtl  Mod  N  P  
0           Normal     208500    1    0  0  0  
1           Normal     181500    1    0  0  0  
2           Normal     223500    1    0  0  0  
3          Abnorml     140000    1    0  0  0  
4           Normal     250000    1    0  0  0  
...            ...        ...  ...  ... .. ..  
1455        Normal     175000    1    0  0  0  
1456        Normal     210000    1    0  0  0  
1457        Normal     266500    1    0  0  0  
1458        Normal     142125    1    0  0  0  
1459        Normal     147500    1    0  0  0  

[1460 rows x 78 columns]

In [34]:
df2.shape

(1460, 78)

In [35]:
numerical_features2=[feature for feature in df2.columns if df2[feature].dtype!='O']
len(numerical_features2)

45

In [36]:
df3=df2[numerical_features2]
df3.shape

(1460, 45)

In [37]:
c_matrix=df3.corr()

In [39]:
sale_price_realations=c_matrix['SalePrice']
sale_price_realations.sort_values(ascending=False)

SalePrice        1.000000
OverallQual      0.790982
GrLivArea        0.708624
GarageCars       0.640409
GarageArea       0.623431
TotalBsmtSF      0.613581
1stFlrSF         0.605852
FullBath         0.560664
TotRmsAbvGrd     0.533723
YearBuilt        0.522897
YearRemodAdd     0.507101
GarageYrBlt      0.486362
MasVnrArea       0.477493
Fireplaces       0.466929
BsmtFinSF1       0.386420
LotFrontage      0.351799
WoodDeckSF       0.324413
2ndFlrSF         0.319334
OpenPorchSF      0.315856
HalfBath         0.284108
LotArea          0.263843
BsmtFullBath     0.227122
BsmtUnfSF        0.214479
BedroomAbvGr     0.168213
ScreenPorch      0.111447
PoolArea         0.092404
MoSold           0.046432
3SsnPorch        0.044584
Mod              0.042981
BsmtFinSF2      -0.011378
Utilities       -0.014314
BsmtHalfBath    -0.016844
MiscVal         -0.021190
Id              -0.021917
LowQualFinSF    -0.025606
YrSold          -0.028923
Street          -0.041036
Gtl             -0.051116
OverallCond 

In [40]:
plus_fifty_features=[feature for feature in df3.columns if c_matrix['SalePrice'][feature]>=0.50]
plus_fifty_features.remove('SalePrice')
plus_fifty_features

['OverallQual',
 'YearBuilt',
 'YearRemodAdd',
 'TotalBsmtSF',
 '1stFlrSF',
 'GrLivArea',
 'FullBath',
 'TotRmsAbvGrd',
 'GarageCars',
 'GarageArea']

In [41]:
len(plus_fifty_features)

10

In [42]:
df4=df3[plus_fifty_features+['SalePrice']]
df4.shape

(1460, 11)

In [43]:
df4.columns

Index(['OverallQual', 'YearBuilt', 'YearRemodAdd', 'TotalBsmtSF', '1stFlrSF',
       'GrLivArea', 'FullBath', 'TotRmsAbvGrd', 'GarageCars', 'GarageArea',
       'SalePrice'],
      dtype='object')

In [44]:
df4.isnull().sum().any()

False

In [45]:
df_null2=null_info(df4)
df_null2

Empty DataFrame
Columns: [Null_feature, Null_values, Percentage of Null values]
Index: []

In [46]:
def filling_Null_values_with_zero(data):
    if data.isnull().sum().any()==False:
        print("No Null data !")
    else:
        print('features having Null values are below:')
        null_features=[feature for feature in data.columns if data[feature].isnull().sum()>0]
        print('Null Features:',null_features)
        data[null_features]=data[null_features].fillna(0)
        print('null values are filled with zero')
        return data

In [47]:
df5=filling_Null_values_with_zero(df4)

No Null data !


In [48]:
df5==None

True

In [49]:
X=df4.drop(['SalePrice'],axis='columns')
X.shape

(1460, 10)

In [50]:
y=df4['SalePrice']
y.shape

(1460,)

In [51]:
X.columns

Index(['OverallQual', 'YearBuilt', 'YearRemodAdd', 'TotalBsmtSF', '1stFlrSF',
       'GrLivArea', 'FullBath', 'TotRmsAbvGrd', 'GarageCars', 'GarageArea'],
      dtype='object')

In [52]:
len(X.columns)

10

In [53]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVC
model_scoring={}
def all_model_scores(model,X,y):
    scores=cross_val_score(model,X,y,cv=10)
    mean_score=scores.mean()
    model_scoring.update({model:mean_score})
    return model_scoring

Model_list=[LinearRegression(),DecisionTreeRegressor(),RandomForestRegressor()]
for model in Model_list:
    score_dict=all_model_scores(model,X,y)
df_Models_scores=pd.DataFrame(score_dict,index=[0])
df_Models_scores

LinearRegression()  DecisionTreeRegressor()  RandomForestRegressor()
0            0.767428                 0.740788                 0.840573

In [54]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=42)

In [55]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((1168, 10), (292, 10), (1168,), (292,))

### features that are selected for training

In [61]:
X_train.shape[1]/df.shape[1]*100

12.345679012345679

In [56]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor()
model.fit(X_train,y_train)

RandomForestRegressor()

In [57]:
print(model.score(X_test,y_test)) 

0.8806736810519643


In [58]:
from sklearn.metrics import mean_squared_error
import numpy as np
predictions = model.predict(X_test)
mse = mean_squared_error(y_test,predictions)
rmse = np.sqrt(mse)
print(mse)
print(rmse)

915271791.434288
30253.45916476805


In [59]:
pred_5=model.predict(X_test[:5])
pred_5

array([138985.25, 313819.54, 116162.  , 165551.7 , 318609.1 ])

In [60]:
np.array(y_test[:5])

array([154500, 325000, 115000, 159000, 315500], dtype=int64)

In [54]:
import pickle
pickle.dump(model,open('ml_model.pkl','wb'))

In [55]:
model2=pickle.load(open('ml_model.pkl','rb'))

In [75]:
np.array(X_test.iloc[0])

array([   6, 1963, 2003, 1059, 1068, 1068,    1,    6,    1,  264],
      dtype=int64)

In [76]:
model2.predict(np.expand_dims(X_test.iloc[0],0))

array([142805.75])

In [ ]:
model2.predict([[6,1963,2003,1059,1068,1068,1,6,1,264]])